### ISSUE TITLE
Investigate Webpack 3 Support

### ISSUE THREAD

**Issue by KraigWalker** [styleguidist/loaders#1]
I'm using Styleguidist in a Weback 3 Project with `loaders`. When installing packages with yarn. the following warning:

    warning "loaders@1.1.3" has incorrect peer dependency "webpack@1 || 2".

This is obviously because Webpack 3 isn't specified as a valid peer dependency, yet nothing in my project appears to be broken. Is it safe to add Webpack 3.x as a valid peer dependency?

**Comment by sapegin** [comment]
This package is deprecated, please use webpack-blocks instead.
